name: covidpk
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  floating_navbar: ^2.0.1
  http: ^0.13.2
  intl: ^0.17.0
  provider: ^5.0.0
  fluttertoast: ^8.0.3
  cloud_firestore: ^1.0.6
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0
  geocoder: ^0.2.1
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  url_launcher: ^6.0.3
  flutter_webview_plugin: ^0.3.10+1
  rflutter_alert: ^1.0.3
  flutter_open_whatsapp: ^0.1.2
  flutter_markdown: ^0.6.1
  flutter_native_splash: ^1.1.8+4
  age: ^0.0.1
  change_app_package_name: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/symptoms/
   - assets/prevention/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
